from resin/%%RESIN_MACHINE_NAME%%-python
WORKDIR /usr/src/app
COPY ./requirements.txt /requirements.txt
RUN pip install -r /requirements.txt
COPY . ./
ENV INITSYSTEM on
CMD ["python /usr/src/app/tweeting.py"]