from resin/%%RESIN_MACHINE_NAME%%-python
WORKDIR /usr/src/app
COPY ./requirements.txt /requirements.txt
RUN pip3 install -r /requirements.txt
COPY . ./
ENV INITSYSTEM on
CMD ["python", "src/tweeting.py"]